api:
  address: "localhost:3000"
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "http://127.0.0.1:3000"
  rate_limit:
    requests_per_second: 100
    burst: 1000
  tls:
    enabled: true
    cert_file: "cert.pem"
    key_file: "key.pem"

p2p:
  address: "localhost:3001"
  bootstrap_peers: []
  max_peers: 100
  ping_interval: "30s"
  ping_timeout: "10s"

logging:
  level: "info"
  format: "json"
  output: "stdout"

blockchain:
  block_type: "golden"
  difficulty: 4
  max_block_size: 1048576  # 1MB
  mining_reward: 50

mining:
  enabled: true
  coin_type: "LEAH"  # For golden blocks, use LEAH, SHIBLUM, etc. For silver blocks, use SENUM, AMNOR, etc.
  auto_start: true
  max_threads: 4
  target_blocks_per_minute: 1 